# Based on:
#   https://toha-guides.netlify.app/posts/getting-started/theme-update/

# Update dependencies

version: 2
updates:
# Update the git submodules
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  - "automerge"
