baseURL: https://atorrescogollo.github.io/

languageCode: es
defaultContentLanguage: es

title: Álvaro Torres Cogollo - Portfolio
theme: toha

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  es:
    languageName: Español
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/atorrescogollo/atorrescogollo.github.io

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  #newsletter:
  #  enable: true

  background: images/background.jpg

  #features:
  #  blog:
  #    enable: true

  footer:
    newsletter:
      enable: false

custom_css:
- "css/custom.css"
